### ISSUE TITLE
UI overlaps after Upgrading to V7 Support Library 25.1.0

### ISSUE THREAD

**Issue by Raheemuddin** [openshopio/openshop.io-android#28] opened 2017-01-12 07:39 UTC
After Upgrading the V7 Support Library to v25.1.0 ], Products UI is drastically shown. Product Images are overlapping with previous category images.
![screenshot_2017-01-12-13-07-05](https://cloud.githubusercontent.com/assets/24952095/21881088/5bfae260-d8c8-11e6-9814-621536b7a56e.png)

**Comment by sanjayitdesires** [comment] 2017-01-16 08:08
I tried upgrading all the support libraries, test libraries and compileSdkVersion to v25.1.0 and this overlapping issue started. One more thing, when you click on any recommended product on the Product screen, it doesn't show the UI.

**Comment by raheemuddin786** [comment] 2017-01-16 10:53
I was able to find the root cause for this issue:
its about the popBackStack implementation in clearBackStack(). I did some workarounds by replacing popBackStackImmediate and other changes.
Currently with my changes its stable for now, but does't guarantee a proper fix.

**Comment by ZelvaJan** [comment] 2017-01-18 14:25
Finally had time to explore these issues, thank you for reporting them. 
New V7 Support Library v25.1.0 brings incompatible lifecycle changes during fragment transaction and few bugs. These issues are reported here https://code.google.com/p/android/issues/detail?id=230526 and here https://code.google.com/p/android/issues/detail?id=230415.
UI overlaps should be fixed in a future version of support library. As a temporary workaround you can replace `popBackStack` with `popBackStackImmediate` in a function `clearBackStack()` as @raheemuddin786 mentioned. However this workaround may cause jerky UI transition.
The second problem in the form of missing UI can be fixed by switching off the new fragment replace optimization, which change the fragments lifecycle. To turn this optimization off simply add `fragmentTransaction.setAllowOptimization(false);` in a function `replaceFragment()`.

**Comment by PkayJava** [comment] 2017-02-13 02:04
for some reason, volley does not perform the add requested. If you use Retrofit2 instead of volley. it would be fine. for this solution, there are many code changes.

**Comment by ZelvaJan** [comment] 2017-03-04 16:30
Fixes merged to master. ab6450c704f92e3fb941dfe2dd26cf11bbcd9aa5

**Closed as completed by ZelvaJan** 2017-03-04 16:30 UTC
